<a href="https://colab.research.google.com/github/eloigil/ai-course/blob/master/09-algebra-in-python/01_dimension_sc_vect_matr_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dimension scalar, vector, matrix, tensor

In [0]:
import numpy as np

In [0]:
scalar = 5.43
vector = np.array([1,2,3])
matrix = np.array([[1,2],[3,3]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
  ])

In [7]:
print(scalar)

5.43


*.shape* method returns the dimension of the element

In [10]:
scalar.shape
# scalars have no shape method

AttributeError: ignored

In [12]:
print(vector)
print(len(vector)) #shows first dimension
print(vector.shape)

[1 2 3]
3
(3,)


In [14]:
print(matrix)
print(len(matrix)) #shows first dimension
print(matrix.shape)
print(matrix.size) #total amount of elements

[[1 2]
 [3 3]]
2
(2, 2)
4


In [15]:
print(tensor)
print(len(tensor)) #shows first dimension
print(tensor.shape)
print(tensor.size) #total amount of elements

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
3
(3, 3, 3)
27
