<a href="https://colab.research.google.com/github/eloigil/ai-course/blob/master/09-algebra-in-python/02_transposition_and_sum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transposition and sum

In [0]:
import numpy as np

In [0]:
scalar = 5.43
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
  ])

In [5]:
vector_t = vector.T
print(vector_t)

[1 2 3]


In [9]:
matrix_t = matrix.T
print(matrix_t)
print(matrix_t.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [10]:
tensor_t = tensor.T
print(tensor_t)
print(tensor_t.shape)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]
(3, 3, 3)


In [16]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3],[4,5,6]])
C = A+B
print(C)

[[ 2  4  6]
 [ 8 10 12]]
