<a href="https://colab.research.google.com/github/eloigil/ai-course/blob/master/09-algebra-in-python/03_matrix_properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [6]:
# Associative
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [7]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [9]:
# Distrubutive
D = A.dot(B+C)
E = A.dot(B)+A.dot(C)
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [11]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [14]:
# Commutative just between vectors
F = B.dot(C)
G = C.dot(B)
print(F)
print(G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]
