<a href="https://colab.research.google.com/github/eloigil/ai-course/blob/master/09-algebra-in-python/06_identity_inverse_singuraity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([[2],[3],[5],[7]])
print(vector)
print(identity.dot(vector))

[[2]
 [3]
 [5]
 [7]]
[[2.]
 [3.]
 [5.]
 [7.]]


In [10]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [11]:
inverse_A = np.linalg.inv(A)
print(inverse_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [13]:
print(A.dot(inverse_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
singular = np.array([[1,1],[1,1]])
print(singular)

[[1 1]
 [1 1]]


In [19]:
print(np.linalg.inv(singular))
# singular matrices have no inverse

LinAlgError: ignored