<a href="https://colab.research.google.com/github/eloigil/ai-course/blob/master/10-linear-algebra-for-ml/03_matrix_decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

### Square matrix decomposition

A=[autovects][autovals_diag][autovects_inv]

In [0]:
A = np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [0]:
autovals, autovects = np.linalg.eig(A)

In [0]:
print(autovals)
print(autovects)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [0]:
A_calc = autovects.dot(np.diag(autovals)).dot(np.linalg.inv(autovects))
print(A_calc)

[[3. 2.]
 [4. 1.]]


---

### Square and Simetric matrix decomposition
if A = A.T

A = [autovects][autovals][autovects.T]

In [0]:
A = np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


In [0]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [0]:
autovals, autovects = np.linalg.eig(A)
print(autovals)
print(autovects)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [0]:
A_calc = autovects.dot(np.diag(autovals)).dot(autovects.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]


---
---


### Non-Square matrix decomposition

In [0]:
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [0]:
# svd singular values
U, D, V = np.linalg.svd(A)

In [0]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [0]:
print(D)
print(np.diag(D))

[7.97638869 0.61418515]
[[7.97638869 0.        ]
 [0.         0.61418515]]


In [0]:
print(V)

#### decomposition

A = U•D_diag•V

D is used as a nexus of different dimensions