In [0]:
import torch
import numpy as np

# Working with tensors
---

In [2]:
torch.__version__

'1.4.0'

In [3]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [7]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[1.3435e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])


tensor([[0.8770, 0.1411],
        [0.8817, 0.9295]])

In [8]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.4373, 0.4185],
        [0.8910, 0.7316]])

In [10]:
result = tensor_a + tensor_b
result

tensor([[1.8770, 1.1411],
        [1.8817, 1.9295]])

In [13]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.8770],
        [1.1411],
        [1.8817],
        [1.9295]])

In [20]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points[0][1])
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [22]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [23]:
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [26]:
tensor_x = torch.tensor([1, 2, 3, 4])
# tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [32]:
numpyArray = np.random.randn(2,2)
torch.from_numpy(numpyArray)

tensor([[-1.7048,  1.7147],
        [ 0.1003, -0.3985]], dtype=torch.float64)